### ISSUE TITLE
Signature still produces bad signatures at times

### ISSUE THREAD

**Issue by autumnpat** [devops-csmake/csmake-swak#10]
The Signature module will produce a signed RpmPackage resulting package with a bad signature occasionally, even when not used in parallel with another signature

**Comment by autumn-cpt** [comment]
The problem is still occurring

**Comment by autumn-cpt** [comment]
In fact it occurs now on signing the swak package

**Comment by autumnpat** [comment]
After running multiple tests, it turns out that the problem is actually something with rpm itself.  The signature produced and added to the rpm is just fine.  Tested the signature by isolating the signature from the rpm using head and tail, and getting all of the bits in the rpm that the signature actually signs and running gpg against this.

A couple of options would be to change the RpmPackage to test a signature and retry on sign fail, or have an aspect module that tests it and retries if the signature fails, or use the list of parameters to gpg as shown in a web page where another packager was having issues....I need to re-find that page.

**Comment by autumn-cpt** [comment]
It wasn't actually the signature itself.  It was the SHA-1.  The SHA-1 needs to be a string representation of the SHA.  Occasionally the SHA-1 will have NUL as one of the characters in the result, when that happens, the string will be cut short, since RPM is expecting a null-terminated string.

Changing the RpmPackage to write a hexdigest instead of a digest fixes the issue
